version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  generar:
    build: './agregar_placas'
    depends_on:
      - redis
    volumes:
      - ./agregar_placas:/code
    command: python alimentar_placas.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis
      
  agente-a:
    build: './lectura_placas'
    depends_on:
      - redis
    volumes:
      - ./lectura_placas:/code
    command: python procesar_placas.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis      

  agente-b:
    build: './lectura_placas'
    depends_on:
      - redis
    volumes:
      - ./lectura_placas:/code
    command: python procesar_placas.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis

  agente-c:
    build: './lectura_placas'
    depends_on:
      - redis
    volumes:
      - ./lectura_placas:/code
    command: python procesar_placas.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis